version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    assignees:
      - constrat
    groups:
      gha:
        patterns:
          - "*"
