name: test

on:
  push:
    paths:
      - '3rdparty/include/**'
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'MAA.sln'
      - 'resource/**'
      - 'MaaDeps/**'
  pull_request:
    paths:
      - '3rdparty/include/**'
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'MAA.sln'
      - 'resource/**'
      - 'MaaDeps/**'
  workflow_dispatch:

jobs:
  smoke-testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Taggify Version
        run: |
          $csprojPath = "src/MaaWpfGui/MaaWpfGui.csproj"
          $csprojPath = Resolve-Path -Path $csprojPath
          [xml]$csproj = Get-Content -Path $csprojPath
          $node = $csproj.Project.PropertyGroup | where {$_.AssemblyName -ne $null}
          $node.InformationalVersion = '${{ needs.meta.outputs.tag }}'
          $node.Version = '${{ needs.meta.outputs.tag }}'
          $node.FileVersion = '${{ needs.meta.outputs.tag }}'
          $node.AssemblyVersion = '${{ needs.meta.outputs.tag }}'
          $csproj.Save($csprojPath)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: NuGet/setup-nuget@v1.2.0
      - run: |
          nuget restore MAA.sln
          if ($LASTEXITCODE) { nuget restore MAA.sln }
          if ($LASTEXITCODE) { nuget restore MAA.sln }
      
      - name: Bootstrap MaaDeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 maadeps-download.py x64-windows
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Build MaaSample
        run: |
          MSBUILD src/Cpp/MaaSample.slnf /t:rebuild /p:Configuration="Debug" /p:Platform="x64" /m

      - name: Run tests
        run: |
          .\x64\Debug\Sample.exe

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: .\x64\Debug\debug
