name: test

on:
  push:
    paths:
      - '3rdparty/include/**'
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'MAA.sln'
      - 'resource/**'
      - 'MaaDeps/**'
  pull_request:
    paths:
      - '3rdparty/include/**'
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'MAA.sln'
      - 'resource/**'
      - 'MaaDeps/**'
  workflow_dispatch:

jobs:
  smoke-testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: Windows-${{ hashFiles('**/global.json', '**/*.csproj') }}
      
      - name: Bootstrap MaaDeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 maadeps-download.py x64-windows
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Build MaaSample
        run: |
          MSBUILD src/Cpp/MaaSample.slnf /t:rebuild /p:Configuration="Debug" /p:Platform="x64" /m

      - name: Run Testing
        run: |
          .\x64\Debug\Sample.exe

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: .\x64\Debug\debug
